### ISSUE TITLE
[help]关于挂梯子或不挂梯子，链接机器人时都报错httpcore.ConnectError

### ISSUE THREAD

**Issue by xiaobai1O1** [nonebot/adapter-discord#45]
11-25 16:39:03 [ERROR] nonebot | Discord | Failed to get gateway info.
Traceback (most recent call last):
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
    yield
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpx\_transports\default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpcore\_async\http_proxy.py", line 288, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpcore\_async\connection.py", line 101, in handle_async_request
    raise exc
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpcore\_async\connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpcore\_async\connection.py", line 156, in _connect
    stream = await stream.start_tls(**kwargs)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpcore\_backends\anyio.py", line 79, in start_tls
    raise exc
  File "C:\Program Files\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\编程专用\discordbot\.venv\lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\nonebot\drivers\none.py", line 61, in run
    anyio.run(self._serve)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\anyio\_core\_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2284, in run
    return runner.run(wrapper())
  File "D:\编程专用\discordbot\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 210, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Program Files\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\编程专用\discordbot\.venv\lib\site-packages\nonebot\adapters\discord\adapter.py", line 81, in run_bot
    gateway_info = await self._get_gateway_bot(bot_info)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\nonebot\adapters\discord\adapter.py", line 131, in _get_gateway_bot
    resp = await self.request(request)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\nonebot\internal\adapter\adapter.py", line 92, in request
    return await self.driver.request(setup)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\nonebot\drivers\httpx.py", line 132, in request
    return await session.request(setup)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\nonebot\drivers\httpx.py", line 78, in request
    response = await self.client.request(
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpx\_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpx\_client.py", line 1674, in send
    response = await self._send_handling_auth(
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpx\_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpx\_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpx\_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpx\_transports\default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Program Files\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\编程专用\discordbot\.venv\lib\site-packages\httpx\_transports\default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

这是报错，在两台win电脑上都试了（一个win10一个win11)
不仅是适配器链接不上，如果用discord的库来链接的话两台电脑开梯子与不开梯子都报错

Traceback (most recent call last):
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1109, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohappyeyeballs\impl.py", line 104, in start_connection
    raise first_exception
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohappyeyeballs\impl.py", line 82, in start_connection
    sock = await _connect_sock(
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohappyeyeballs\impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\编程专用\discordrobottest.py", line 15, in <module>
    bot.run(token)
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 869, in run
    asyncio.run(runner())
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 858, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 786, in start
    await self.login(token)
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 620, in login
    data = await self.http.static_login(token)
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\discord\http.py", line 816, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\discord\http.py", line 638, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 1423, in __aenter__
    self._resp: _RetType = await self._coro
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 701, in _request
    conn = await self._connector.connect(
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1394, in _create_direct_connection
    raise last_exc
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1363, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\xuqiang\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1124, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [信号灯超时时间已到]

但有趣的是
在手机上，通过pydroid3，使用discord的库，挂上梯子，却能成功链接机器人并上线响应指令

**Comment by xiaobai1O1** [comment]
已解决（clash开启Tun模式不开系统代理就能连上了

**Comment by Autuamn** [comment]
试试在 `.env` 文件添加配置项：`DISCORD_PROXY='http://<代理地址>'`，driver 换用 `aiohttp`

---
可以看看配置吗，注意清除隐私信息

提交日志最好把日志等级调到 `TRACE`

日志最好写在代码块里，像这样：
~~~markdown
```
[日志写在这里]
```
~~~
